import type { Metadata } from 'next';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import Footer from '../components/Footer';
import Header from '../components/Header';
import ErrorBoundary from '../components/ErrorBoundary/page';
import './globals.css';



const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'RSS-GraphiQL',
  description: 'Generated by create next-GraphiQL app',
};

const RootLayout = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  return (
    <ErrorBoundary>
      <html lang="en">
        <Head>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <body className={inter.className}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ErrorBoundary>
  );
};

export default RootLayout;
